### PR TITLE
fix(RequestAnimationFrame): pass the timestamp to the callback

### LINKED ISSUE #187: requestAnimationFrame callback arguments not passed in
In alpha36, a requestAnimationFrame's callback correctly gets the timestamp argument:
http://plnkr.co/edit/6ZkphwlO7hUKpoLrBDJw?p=preview

In alpha37, the rAF callback does not get the timestamp argument:
http://plnkr.co/edit/H9bYRx7gDivc5qxkdVB1?p=preview

This causes javascript animations to fail.

Also close: https://github.com/angular/angular/issues/4179

### PR DESCRIPTION
**Pull request by vicb**
fixes #187

### CODE REVIEW

**Comment by vicb** [comment]
@mhevery could you please review ?

/cc @justindujardin

**Comment by justindujardin** [comment]
Nice fix and test. :+1:

**Comment by btford** [comment]
LGTM

**Comment by vicb** [comment]
@btford Thanks for the review

**Pull request merged**
