### PR TITLE
refactor: changed a named function to be anonymous

### PR DESCRIPTION
**Pull request by vicb**

### CODE REVIEW

**Comment by btford** [comment]
Why?

**Comment by vicb** [comment]
Why not ?

Actually consistency. Maybe I'm too much obsess about consistency but I find harder to understand a piece of code when multiple different conventions are used. 

If you consider merging this please wait there are other minor cleanups that I could squash here, if not feel free to close.

**Comment by pkozlowski-opensource** [comment]
So the only one thing I've got "against" anonymous functions is that debugging gets harder. So if we are after consistency I would rather name all the functions.

(once again, sorry for just chiming in with style issues, still trying to wrap my head around the zone thing)

**Comment by btford** [comment]
This fn appears in stacktraces sometimes, so having a name makes it a bit easier when looking at stacktraces.

**Comment by vicb** [comment]
I haven't thought about it makes sense, closing this PR. Thanks for your help.

@pkozlowski-opensource I appreciate your comments, no problem. May be we can discuss about zones some day, I'm working quite a lot around it these days.

**Pull request closed without merging**
