### PR TITLE
Fixes XSS errors occurring in Firefox and WebDriver

### PR DESCRIPTION
**Pull request by spinfooser**
Also improved some documentation/scripting for tests.

This will make cross-site scripting errors go down for feature testing using Selenium or Protractor frameworks.

### CODE REVIEW

**Comment by spinfooser** [comment]
I'm finding it difficult to figure out why this build failed. Any ideas @mhevery ?

**Comment by mhevery** [comment]
Can you make sure that you install Chrome 42.0.2311 on your local machine to reproduce it?

**Comment by spinfooser** [comment]
I had issues reproducing this issue after installing Chrome 42.0.2311.90 on a Debian x64 Linux machine. I don't understand what could be different between a SauceLabs machine and this Virtual machine I'm using, but unfortunately there is. If I had access to a SauceLabs container, I could probably find the issue pretty quickly.

Here is a screenshot of a different failing test when I run tests with the above configuration on a clean copy of the codebase (9b3e77988a54824ee97a3277cc192ab442cdb788):

[Screenshot of different failing test](http://imgur.com/Wa8AQg6)

These failures are from very different areas of code, so I'm not quite sure what to make of it except for fragile tests potentially?

For reference: the failure in CI for this pull request is `Chrome 42.0.2311 (Linux 0.0.0) HTML Imports should work with addEventListener FAILED`.  Is it possible that timing differences associated with machine speed are causing this?

**Comment by spinfooser** [comment]
I did a rebase with the recent changes from master and the tests now pass. This was likely a flaky test issue. I'm going to reopen a pull request with only my patch.

**Pull request closed without merging**
