### PR TITLE
ensure zoneDelegates is not null before updateTask.

### PR DESCRIPTION
**Pull request by aitboudad**

### CODE REVIEW

**Comment by aitboudad** [comment]
somehow it getting null when I use https://github.com/matthieua/WOW in angular also zoneDelegates can be nullable looks at https://github.com/angular/zone.js/blob/master/lib/zone.ts#L879

**Comment by JiaLiPassion** [comment]
@aitboudad , can you provide a reproduce repo? I think just check null will not really resolve the issue.

**Comment by aitboudad** [comment]
ok I'll try

**Comment by aitboudad** [comment]
can't reproduce it anymore since the last release

**Pull request closed without merging**
