### PR TITLE
feat(build): Upgrade to TypeScript 2.9 and rxjs6

### LINKED ISSUE #1091: RxJs 6 Support
The `zone-patch-rxjs.js` fails to build with rxjs 6.x that Angular 6 uses now. Any plan on fixing this?

### PR DESCRIPTION
**Pull request by JiaLiPassion**
This includes a migration to TS2.9, and a migration to RxJS 6 (which is required for TS2.9 support).

fix #1091.

And this PR is based on #1104, thanks for @mprobst's great help!

### CODE REVIEW

**Comment by mprobst** [comment]
@googlebot I herewith confirm that I am OK with my commits being contributed to this project.

**Comment by sssalib42** [comment]
@JiaLiPassion , and @mprobst @googlebot  can we please complete this PR! It's literally that last thing stopping me from completing my last step in RxJS 6 process which is removing rxjs-compat....

Come on now! The updated was like back in April...

**Comment by JiaLiPassion** [comment]
@sssalib42, I am not sure the release schedule, please use the following branch as temp test solution.
update the `package.json` 
```
"zone.js": "git://github.com/JiaLiPassion/zone.js#ts29-fix-dist"
```

**Comment by arusak** [comment]
Would somebody please satisfy this horny bot?

**Comment by JiaLiPassion** [comment]
@arusak, the `bot` is not a real issue, after the review, it can be merged ignore this `bot error`.

**Comment by sssalib42** [comment]
Author consent!? How can we fix the cal/google error requiring an author consent verification?
@JiaLiPassion @mprobst @googlebot

**Comment by sssalib42** [comment]
@IgorMinar @mhevery @robwormald @StephenFluin @alxhub @benlesh

Angular 7 is coming out in the next few weeks and we still can't completely upgrade to Angular 6!

**Comment by sssalib42** [comment]
Thank you @mhevery!!! I'm so happy to have come so close from interacting with the founder, and the man who started it all. The Father of Angular :):):)

**Pull request merged**
