### PR TITLE
fix(jasmine patch): forward timeout

### PR DESCRIPTION
**Pull request by mlaval**
Needed to run Angular2 unit tests in SauceLabs, see https://github.com/angular/angular/pull/2347

[Review on Reviewable](https://reviewable.io/reviews/angular/zone.js/139)

### CODE REVIEW

**Comment by vicb** [comment]
LGTM

**Comment by mlaval** [comment]
I can't merge here. Could someone take care of it please?

**Comment by vicb** [comment]
@mlaval I'll merge this and prepare a new release later today

**Comment by mlaval** [comment]
Landed as 2dde7171c4e0bf1ab18d899ab3949861b930f588

**Pull request closed without merging**
