### PR TITLE
chore: release v0.8.27

### PR DESCRIPTION
**Pull request by CaerusKaru**

### CODE REVIEW

**Comment by CaerusKaru** [comment]
cc @mhevery

**Comment by JiaLiPassion** [comment]
@CaerusKaru , could we also include those 3 PRs?
1. https://github.com/angular/zone.js/pull/1121
2. https://github.com/angular/zone.js/pull/1113
3. https://github.com/angular/zone.js/pull/1156

Thanks!

**Comment by CaerusKaru** [comment]
@mhevery I've rebased this PR and updated the CHANGELOG. Once CI passes, it should be good to go.

**Comment by CaerusKaru** [comment]
@JiaLiPassion Can you help diagnose the CI failures?

**Comment by JiaLiPassion** [comment]
@CaerusKaru, @mhevery, `CI` is happy now, let's cut a new release, thanks a lot!

**Comment by coutin** [comment]
Any news about getting the new version out ?

**Comment by JiaLiPassion** [comment]
`0.8.27` is live in npm now!

**Comment by MattiJarvinen-BA** [comment]
You released unmerged version?!?

**Comment by JiaLiPassion** [comment]
@MattiJarvinen-BA, this PR will be merged tomorrow, and the version on `npm` is the same with this PR's commit.

**Comment by MattiJarvinen-BA** [comment]
Just got me confused, because I came here to read the changelog.

**Pull request merged**
