### PR TITLE
(updated) fix: commonjs wrapper

### LINKED ISSUE #19: Does not seem to be browserify compatible
Even if I try to:
```javascript
window.zone = require('zone.js');
```
I get ```zone is not defined``` because the function Zone.patchSetClearFn assumes window.zone exists (i.e. in line 133).

Perhaps Zone.init should just installs on window.zone independently of module.exports, but export the created instance as well. 

Any thoughts?

### PR DESCRIPTION
**Pull request by unframework**
This is a rebase and tweak of original commonjs wrapper fix: https://github.com/angular/zone.js/pull/22

Closes #19

### CODE REVIEW

**Comment by btford** [comment]
It'd be nice to have a test showing that this works.

**Comment by unframework** [comment]
@btford thanks for the response! I just added a test using karma-browserify; also had to tweak the original implementation because it inadvertently masked original window reference for property patching.

**Comment by unframework** [comment]
... not sure if the test failures were there from before - the code seems to work OK in my local browserify setup in Chrome and FF.

**Comment by unframework** [comment]
I created a temp npm package to be able to reference this as a dependency. Will remove once merged.

**Comment by btford** [comment]
@unframework – FYI you can `npm install unframework/zone.js` and npm will grab your stuff from github. It's better not to pollute the npm namespace, even if only temporarily.

**Comment by unframework** [comment]
Hey thanks for the tip, I forgot about that `package.json` feature. Removed the temp package, using the Git dependency now

**Comment by btford** [comment]
Landed as 5d6bee4b47d82a8cf1cde76ce19b70350a67ff10.

I'll cut a release with this sometime soon.

**Comment by ocombe** [comment]
Ahh nice, waiting for this release as well :)

**Comment by ocombe** [comment]
By the way, you'll have to edit the following file https://github.com/angular/angular/blob/master/modules/angular2/src/core/zone/vm_turn_zone.es6 to make it work with your changes (you probably know that already), I tested it locally and it works with webpack now (I edited this file from angular2 to test)

**Pull request closed without merging**
