### PR TITLE
[WIP] feat(Node): make zone.js work in Node

### PR DESCRIPTION
**Pull request by vicb**
This is a port of @mlaval #78 to zone 0.5

relates to https://github.com/angular/angular/issues/1904 & the short term plan described there

/cc @tbosch @IgorMinar

Edit: 
- before merging we should discuss if the short term plan defined in the linked PR makes sense,
- I'd like to find a good solution to distribute both zone.js and zone-microtask.js (have different repos ?)

[Review on Reviewable](https://reviewable.io/reviews/angular/zone.js/116)

### CODE REVIEW

**Comment by vicb** [comment]
@btford It is not comprehensive, see the linked PR for more info

**Comment by matthewjh** [comment]
@vicb: does Zone work in node now?

**Comment by vicb** [comment]
Not that I know

**Comment by matthewjh** [comment]
In that case, I can take a look at how node environments can be supported. Seems like it could be interesting.

Is that OK or have you got separate plans to tackle this?

**Comment by vicb** [comment]
That would be great !

**Comment by boneskull** [comment]
also see [continuation-local-storage](https://www.npmjs.com/package/continuation-local-storage)

**Comment by mhevery** [comment]
obsolete. Latest zone works on node.

**Comment by boneskull** [comment]
What versions?

**Comment by mhevery** [comment]
v0.6.4.  (But we don't patch node's API)

**Comment by boneskull** [comment]
right, this is problematic.  it seems like a fool's errand to try to patch every async API method in every possible environment.  hope the proposal works out--from where I sit, the only feasible solution is something at the specification level.

**Pull request closed without merging**
