### PR TITLE
[WIP] chore(Travis): Spin up a WS server

### PR DESCRIPTION
**Pull request by vicb**
I'm working with the SL support to get this working.

### CODE REVIEW

**Comment by vicb** [comment]
Thanks to the SL support and @DylanLacey we are close to a working solution (except for Safari for now). Thanks Dylan

see https://github.com/DylanLacey/zone.js

**Comment by vicb** [comment]
@DylanLacey, any update wrt to Safari ? Thanks

**Comment by DylanLacey** [comment]
@vicb Sorry, was out sick.

I've got a passing build on Safari;  There's a stupid edge case where Safari refuses to use send traffic for localhost or 127.0.0.1 through Sauce Connect first, and so websocket requests were 502-ing.

I worked around this by explicitly specifying a hostname.  Normally, you'd have to use your machine's hostname or edit your hosts file, which would confuse karma because the browser's hostname isn't the same as the remote server, so I used the `WEBSOCKET_HOST` environment variable and used [envify](https://github.com/hughsk/envify) as a transform step with browserify to replace this with the hostname of the machine running the tests.

I also edited .travis.yml to ensure Travis gives the machine a hostname.  And now the tests pass on all platforms.

I can either send a PR directly to zone.js, or I can send it to your fork, @vicb, what's preferable?

**Comment by vicb** [comment]
@DylanLacey thank you so much. Could you please send the PR to zone.js (you'll have to sign the CLA I think).

**Comment by DylanLacey** [comment]
Not a problem!  I'm all good to go, I just can't find the CLA.

**Pull request closed without merging**
