### PR TITLE
feat(custom-element): patch customElement v1 APIs

### PR DESCRIPTION
**Pull request by JiaLiPassion**
Patch the `CustomElement V1` APIs.

```
connectedCallback
disconnectedCallback
adoptedCallback
attributeChangedCallback
```
Make them run in the `zone` when they were `defined by customElements.define`.

So the issue like https://github.com/angular/angular/pull/24185 may be resolved by this one.

@robwormald, @mhevery, please review, thank you!

### CODE REVIEW

**Comment by remackgeek** [comment]
This is cool!  Does it play nice with the document-register-element polyfill (specifically 1.8.1)?

**Comment by JiaLiPassion** [comment]
@remackgeek, I believe before this PR, `zone.js` already support `legacy document.registerElement`. So `document-register-element` polyfill will also be supported.

**Comment by krishna217** [comment]
Which version will this issue be fixed ?

**Comment by antch** [comment]
Just FYI for anyone following the thread, this fix is available as of 0.8.27.

**Comment by harveyelsisura** [comment]
@antch where?

**Pull request merged**
