### PR TITLE
fix(event): fix #1110, nodejs EventEmitter should support Symbol eventName

### LINKED ISSUE #1110: makeAddListener breaks when the Event Name is a Symbol
When Zone.js is running in Node, it appears to be wrapping Node's EventEmitter methods, causing issues when the `eventName` is a Symbol. Node's [documentation states that `eventName` can be a string or a symbol.](https://nodejs.org/api/events.html#events_emitter_on_eventname_listener)

However, Zone tries to coerce `eventName` into a string:

https://github.com/angular/zone.js/blob/e9536ec7d724e21473496c090378d6635944c798/lib/common/events.ts#L383

This causes an error:

```
TypeError: Cannot convert a Symbol value to a string
    at Unpack.<anonymous> (zone.js/dist/zone-node.js:1688:52)
    at new Parser (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/parse.js:70:12)
    at new <anonymous> (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/warn-mixin.js:2:26)
    at new Unpack (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/unpack.js:52:5)
    at extract (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/extract.js:111:10)
    at Object.module.exports (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/extract.js:38:7)
    at extractStream (/gulp-custom-plugin/node_modules/custom-module/node_modules/pacote/lib/extract-stream.js:39:1
```

This is causing an issue in the `node-tar` library, [for instance](https://github.com/npm/node-tar/issues/189).

### PR DESCRIPTION
**Pull request by JiaLiPassion**
fix #1110.

In nodejs, `EventEmitter` should support `Symbol` as `eventName`.

```ts
const symbolA = Symbol('A');
emitter.addListener(symbolA, listener);
emitter.removeListener(symbolA, listener);
```

### CODE REVIEW

**Comment by jreidgreer** [comment]
@JiaLiPassion do you happen to know when this will get merged? Thanks!

**Comment by jreidgreer** [comment]
@JiaLiPassion do you have an update on when this might be merged in?

**Comment by JiaLiPassion** [comment]
@jreidgreer, I am not sure, If you want to test, I can create a temp release branch for you.

**Comment by Mathyn** [comment]
Any updates on this? When can we expect this to be released?

**Pull request merged**
