### PR TITLE
test(WebSocket): enable WS with Sauce Connect

### PR DESCRIPTION
**Pull request by vicb**
@DylanLacey could you please make sure you sign the CLA at https://cla.developers.google.com/clas

I have done some cleanup on your original PR #123

[Review on Reviewable](https://reviewable.io/reviews/angular/zone.js/124)

### CODE REVIEW

**Comment by DylanLacey** [comment]
Oh, thanks!  Sorry, my day had ended.  I've signed the CLA.

**Comment by vicb** [comment]
@DylanLacey no problem, thanks.

Still have to fix the issue with WS in IE before this can get merged.

**Comment by DylanLacey** [comment]
We can delete this PR though?

**Comment by vicb** [comment]
We need to fix the issue with IE first - which is s real bug in the lib before we can merge - not delete - the PR. To be clear this is no related to sauce but a bug that wasn't tested before

**Comment by DylanLacey** [comment]
@vicb Oh, sorry, I got confused and thought this was my PR, not yours.

**Comment by vicb** [comment]
your code, my pr :)

**Comment by DylanLacey** [comment]
Yup yup :P  Oh and @googlebot and your human handlers, I am A-OK with this code being contributed and I agree with the CLA.

**Comment by mhevery** [comment]
Any chance we could rebase this on the latest master?

**Comment by mhevery** [comment]
abandoned

**Pull request closed without merging**
