### PR TITLE
Added property patches and event target methods as well as tests for Indexed DB

### PR DESCRIPTION
**Pull request by gionkunz**
This does solve #202 , although I still have problems with PuchDB as described in #203 . I tested in Firefox and Chrome.

### CODE REVIEW

**Comment by cherrydev** [comment]
@gionkunz Any luck on getting this patch working with tests running?  I'm not sure why this failed to begin with, but I notice that at least currently, the idiom for the tests is to use the `global.zone` reference instead of just `zone`.

**Comment by mhevery** [comment]
Could we get this rebased on the latest master?

**Comment by gdi2290** [comment]
IndexedDB support would be great

**Comment by mhevery** [comment]
@gdi2290 could you rebase this on master so that we could merge this in?

**Comment by mhevery** [comment]
abandoned

**Pull request closed without merging**
