### PR TITLE
test: exclude WS tests for Sauce

### PR DESCRIPTION
**Pull request by vicb**

### CODE REVIEW

**Comment by vicb** [comment]
It would be great to finally see Travis green.

It is still not after this PR because of the CJS tests but at least this PR do what's advertised.

**Comment by btford** [comment]
According to their documentation, Sauce Connect should support websockets. Is this no longer the case?

**Comment by vicb** [comment]
Nope it is not that simple - tried that in a closed PR.
I'll try to contact their support next week but before we get an answer, this patch is meaningful. No need to run tests we know are red. It gives the bad habit of stop caring about Travis results.

**Comment by IgorMinar** [comment]
I thought that karma used websockets on SL, but it doesn't. I agree that we should disable the ws test on sauce for now. Maybe we could add write at least one test that would fake ws communication or at least check if the ws methods are being patched.

**Comment by IgorMinar** [comment]
more on this in #41

**Comment by IgorMinar** [comment]
I'm going to merge this in to get the build into a better state.

**Pull request closed without merging**
