### PR TITLE
Progress to TypeScript 2.9.

### PR DESCRIPTION
**Pull request by mprobst**
This includes a partial migration to TS2.9, and a partial migration to RxJS 6 (which is required for TS2.9 support).

### CODE REVIEW

**Comment by mprobst** [comment]
Hey @JiaLiPassion  - I started to look into this a bit, but couldn't quite finish through (I don't understand some of the RxJS operations). Maybe this is still helpful for you?

**Comment by mprobst** [comment]
This is a partial fix for #1104.

**Comment by JiaLiPassion** [comment]
@mprobst , thank you for the PR, it is a great help. 
I am doing the same thing too, the difficult part is I want to make two `rxjs` bundle which can support `rxjs 5.x` and `rxjs 6+`, so it takes some time to re-structure the folder/tsconfig.json/gulpfile/travis, I want `zone.js` can build/test both `rxjs5` and `rxjs6`.

But I think `rxjs 6`'s priority is higher, so I can review this PR now, and after this PR is OK and merged, I will add support to `rxjs 5` later.

**Comment by JiaLiPassion** [comment]
@mprobst , and could you rebase the PR to the latest version? Some compilation error occurs in CI.

**Comment by mprobst** [comment]
I think it's up to date with master, but as I said, it's partial - I
haven't managed to figure out the rxSubscription symbol compilation error
(not sure how that'll work in rxjs 6).

**Comment by JiaLiPassion** [comment]
@mprobst , I will checkout your branch to find out.

**Comment by JiaLiPassion** [comment]
@mprobst, I have made all compiler error gone, and I am trying to make all test cases pass, after that I will make a PR to your branch.

**Comment by mprobst** [comment]
Thanks Jia!

**Comment by JiaLiPassion** [comment]
sorry for the delay, I have fixed all the test cases, and I created a PR to your branch, but I rebased from current master, so there are lot of conflicts, could you do a force merge to accept all my commits? Thank you.

**Comment by mprobst** [comment]
@JiaLiPassion maybe it's easier if you just take over the pull request entirely and push it yourself? I'm OK with you taking over my small patch (and you did most of the work anyway, I'm sure).

**Comment by JiaLiPassion** [comment]
@mprobst, Sure, got it, thank you for the great help!

**Pull request closed without merging**
