### PR TITLE
fix #591, make ZoneAwarePromise pass promise a+ test

### LINKED ISSUE #591: Make ZoneAwarePromise pass promiseA+ test.
I tried to make ZoneAwarePromise pass promiseA+ test. And found several issues.
The spec is [here](https://github.com/promises-aplus/promises-spec)
The testcase is [here](https://github.com/promises-aplus/promises-tests)

1. 2.2.5
`onFulfilled` and `onRejected` must be called as functions (i.e. with no `this` value).
in strict mode, this should be undefined.

2. 2.2.7.2
If either `onFulfilled` or `onRejected` throws an exception `e`, `promise2` must be rejected "with `e` as the reason

3. 2.3.1
If `promise` and `x` refer to the same object, reject `promise` with a `TypeError' as the reason

4. 2.3.3
Thenable related method should be only called once.
value.then should only be get once.

5. 2.3.4
Thenable should check value is object or function.

### PR DESCRIPTION
**Pull request by JiaLiPassion**
Fix #591, make ZoneAwarePromise pass promise a+ test, and fix several promise issues described 
in #591.

add promise aplus test adapter, promise-adapter.js
we can run promises-aplus-tests promise-adapter.js to see the result

### CODE REVIEW

**Comment by mhevery** [comment]
I don't see how the a+ tests are run? Is it not part of this PR? could it be?

**Comment by JiaLiPassion** [comment]
@mhevery , I will add a npm run scripts now, please wait for a minute.

**Comment by mhevery** [comment]
Allso make sure that it will run on travis.

**Comment by JiaLiPassion** [comment]
> Allso make sure that it will run on travis.

@mhevery, ok, got it.

**Comment by JiaLiPassion** [comment]
@mhevery , I have added the build scripts and added it into travis, now the travis build failed because of the previous android 4.4 setInterval issue, the promise test has passed, please review.

**Comment by mhevery** [comment]
I had to revert this due to https://travis-ci.org/angular/zone.js/builds/194596043 Can you have a look and create a new PR?

**Comment by JiaLiPassion** [comment]
@mhevery , sure, I believe  https://travis-ci.org/angular/zone.js/builds/194596043 failed beause saucelabs android 5.1 is not connected, promise A+ test has passed (although a lot of error log was printed, it is just uncaught promise error log).

**Comment by mhevery** [comment]
I see, you are right it is passing now:
https://travis-ci.org/angular/zone.js/builds/194647163

The reason I got confused is that there are a lot of console.logs with
errors and stack traces. Could we fix the code so that expected errors
don't show up in the log?

-- Misko

**Comment by JiaLiPassion** [comment]
@mhevery, yes, I agree with you,  the log was output by consoleError method when get an uncaught promise error, should we totally remove the consoleError method or just ignore it in the promsie a+ test?

**Comment by mhevery** [comment]
Just remove it in the test. I think it is useful for the developer.

**Comment by JiaLiPassion** [comment]
Ok, working on it.

**Pull request merged**
