### PR TITLE
fix(WebWorker): Fix patching in WebWorker

### PR DESCRIPTION
**Pull request by jteplitz602**

### CODE REVIEW

**Comment by vicb** [comment]
Jason, please do not include the updated dist files in the PR, we update them on releases only.

Also what about some isWebWorker() function ? It would make the intent of the code clearer (also document is not available in a node env. It would be easier to update at only once place).

**Comment by jteplitz602** [comment]
Sorry about the dist folder. Updated the commit to not include it and created isWebWorker in the utils file

**Comment by vicb** [comment]
Thanks for the updates.  LGTM.

**Comment by jteplitz602** [comment]
Cool. I don't have write access to this repo so can you merge it in when you get a chance?

**Comment by vicb** [comment]
landed as 2cc59d8b1b8736df0fac01a71ef2bd8d5c526cb7

**Comment by btford** [comment]
:clap: Thanks @jteplitz602 and @vicb!

**Pull request closed without merging**
