### PR TITLE
Add a `flush` method to the FakeAsync zone spec

### LINKED ISSUE #735: Feature request: FakeAsync should have a flush function
This function would simulate moving time forward until the queue of pending macrotasks is cleared.
With multiple setTimeouts, it would move to the furthest in the future.
It would clear chained setTimeouts.
Intervals would not affect it.

For example (using end-user syntax based on Angular's helpers):

```js
fakeAsync(() => {
  let x = y = z = 0;
  setTimeout(() => { x++; }, 100);
  setTimeout(() => { y++; }, 7000);
  setInterval(() => { z++; }, 100);

  flush();

  expect(x).toEqual(1);
  expect(y).toEqual(1);
  expect(z).toEqual(7);
});

fakeAsync(() => {
  let x = y = z = 0;
  setTimeout(() => {
    x++;
    setTimeout(() => {
      y++;
    }, 100);
  }, 200);
  setInterval(() => { z++; }, 100);

  flush();

  expect(x).toEqual(1);
  expect(y).toEqual(1);
  expect(z).toEqual(3);
});

fakeAsync(() => {
  let z = 0;
  setInterval(() => { z++; }, 100);
  
  flush();

  expect(z).toEqual(0);
});
```

### PR DESCRIPTION
**Pull request by juliemr**
The `flush` method advances time until all non-periodic timers
are cleared from the queue. It has a configurable limit (default 20)
of tasks that will be run before it gives up and throws an error,
in order to avoid infinite loops when polling timeouts are present.

Closes #735

### CODE REVIEW

**Comment by mhevery** [comment]
It seems to be failing CI. Could you have a look? Is it ready to merge?

**Comment by juliemr** [comment]
It looks like IE is unhappy about something - I'll debug.

**Comment by juliemr** [comment]
IE is now happy! I think this is ready for merge unless @vikerman would like to comment.

**Comment by vikerman** [comment]
LGTM

**Pull request merged**
